version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_PORT_SSL}:443
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/nginx/certs:/etc/nginx/certs
      - ./../:/home/wwwroot
      - /home/wwwroot/docker
      - /home/wwwroot/.idea
    depends_on:
      - php

  mysql:
    image: mariadb:latest
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: mysqld --innodb-flush-method=O_DSYNC --general_log=on --general_log_file=/var/lib/mysql/logs/mysql_log_query.log

  php:
    build: config/php
    volumes:
      - ./config/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./../:/home/wwwroot
      - /home/wwwroot/docker
      - /home/wwwroot/.idea
    tmpfs:
      - /home/wwwroot/var/cache
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal idekey=${HOSTNAME}"
      PHP_IDE_CONFIG: "serverName=${HOSTNAME}"

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}


  maildev:
    image: maildev/maildev
    ports:
      - ${MAILDEV_PORT}:80

networks:
  default:
    external:
      name: ${LOCAL_NETWORK}

volumes:
  db-data: